import {
  LayoutDashboard,
  Building,
  Users,
  Calendar,
  Settings,
  Search,
  Plus,
  User,
  BarChart3,
  Home,
  ChevronDown,
  Edit,
  Trash,
  LogOut,
  MessageCircle,
  MapPin,
  Square,
  X,
  Lock,
  LucideProps
} from 'lucide-react';

// Iconos modernos usando Lucide React
export const Icons = {
  Dashboard: (props?: LucideProps) => <LayoutDashboard className="w-5 h-5" {...props} />,
  Properties: (props?: LucideProps) => <Building className="w-5 h-5" {...props} />,
  Clients: (props?: LucideProps) => <Users className="w-5 h-5" {...props} />,
  Visits: (props?: LucideProps) => <Calendar className="w-5 h-5" {...props} />,
  Settings: (props?: LucideProps) => <Settings className="w-5 h-5" {...props} />,
  Search: (props?: LucideProps) => <Search className="w-5 h-5" {...props} />,
  Plus: (props?: LucideProps) => <Plus className="w-5 h-5" {...props} />,
  User: (props?: LucideProps) => <User className="w-5 h-5" {...props} />,
  Stats: (props?: LucideProps) => <BarChart3 className="w-5 h-5" {...props} />,
  Home: (props?: LucideProps) => <Home className="w-5 h-5" {...props} />,
  ChevronDown: (props?: LucideProps) => <ChevronDown className="w-4 h-4" {...props} />,
  Edit: (props?: LucideProps) => <Edit className="w-4 h-4" {...props} />,
  Delete: (props?: LucideProps) => <Trash className="w-4 h-4" {...props} />,
  Trash: (props?: LucideProps) => <Trash className="w-4 h-4" {...props} />,
  LogOut: (props?: LucideProps) => <LogOut className="w-4 h-4" {...props} />,
  Feedback: (props?: LucideProps) => <MessageCircle className="w-5 h-5" {...props} />,
  MapPin: (props?: LucideProps) => <MapPin className="w-4 h-4" {...props} />,
  Square: (props?: LucideProps) => <Square className="w-4 h-4" {...props} />,
  X: (props?: LucideProps) => <X className="w-4 h-4" {...props} />,
  Lock: (props?: LucideProps) => <Lock className="w-5 h-5" {...props} />,
};
